#!/bin/bash

# give the manually built varnish precedence on joyent
export PATH=/home/node/varnish-2.1.3/sbin:$PATH

hostname=`hostname`
varnishd=`which varnishd`

if [ "$hostname" == "team-soundcloud" ] ; then
  echo "starting $varnishd on 127.0.0.1:9000 (live)"
  $varnishd -a 127.0.0.1:9000 -s malloc -n /tmp -f varnish.live.conf
else
  echo "starting $varnishd on 0.0.0.0:9000 (dev)"
  $varnishd -a 0.0.0.0:9000 -s malloc -n /tmp -f varnish.dev.conf
fi
