require 'rake/clean'
CLEAN.include('varnish', 'varnish.dSYM', 'build', '.lock-wscript')

task :default => :build

task :configure do
  sh "node-waf configure" unless uptodate?('.lock-wscript', ['wscript'])
end

task :build => :configure do
  sh "node-waf build"
end

task :test => :build do
  File.open('test.js', 'w') do |f|
    f << %Q[
    var v = require('./build/default/varnish');
    ]
  end
  sh "node test.js"
end

desc "starts varnish"
task :start do
  require 'webrick'
  s = WEBrick::HTTPServer.new(:Port => 8000, :DocumentRoot => File.dirname(__FILE__))
  ['TERM', 'INT'].each do |signal|
    trap(signal) { s.shutdown }
  end
  Thread.new { s.start }
  sh "varnishd -a 127.0.0.1:4000 -b 127.0.0.1:8000 -F -s malloc"
end
