require 'rake/clean'
CLEAN.include('varnish', 'varnish.dSYM', 'build')

task :default => :compile
task :compile do
   sh "gcc varnish.c -g -I/usr/local/include/varnish -lvarnish -lvarnishapi -Wall -L/usr/local/lib -o varnish"
end




desc "starts varnish"
task :start do
  require 'webrick'
  s = WEBrick::HTTPServer.new(:Port => 8000, :DocumentRoot => File.dirname(__FILE__))
  ['TERM', 'INT'].each do |signal|
    trap(signal) { s.shutdown }
  end
  Thread.new { s.start }
  sh "varnishd -a 127.0.0.1:4000 -b 127.0.0.1:8000 -F -s malloc"
end
